language: node_js
node_js:
 - "node"

before_install:
  - bash scripts/current_action.sh

script:
  - 'echo "Build started"'
  - printenv | grep -E "^TRAVIS_"
  - 'echo "Build succeed"'
  - bash scripts/dispatcher.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy_on_tag.sh
    on:
      tags: true