language: node_js
node_js:
 - "node"

script:
  - 'echo "Build succeed"'

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy_on_tag.sh
    on:
      tags: true