#!/bin/bash


echo "==ENV=="
echo "TRAVIS_EVENT_TYPE: $TRAVIS_EVENT_TYPE"

echo "TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST"
echo "TRAVIS_PULL_REQUEST_BRANCH: $TRAVIS_PULL_REQUEST_BRANCH"
echo "TRAVIS_PULL_REQUEST_SLUG: $TRAVIS_PULL_REQUEST_SLUG"

echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"

echo "TRAVIS_TAG: $TRAVIS_TAG"

# PR_TO_DEVELOP
# MERGE_TO_DEVELOP
# PR_TO_MASTER
# MERGE_TO_MASTER
# TAG_ON_MASTER
# TAG_ON_DEVELOP
# TAG_ON_FEATURE

GIT_EVENT="UNKNOWN"
